import Head from "next/head";
import LayoutDark from "@/components/Layout/LayoutDark";
import style from "./about.module.scss";
import Spacer from "@/components/BaseElements/Spacer";
import React from "react";
import FurtherReadingSection from "@/components/Sections/FurtherReadingSection/FurtherReadingSection";
import { motion } from "motion/react";
import Link from "next/link";

export default function Index() {
    return (
        <>
            <Head>
                <title>Labour History Activism - About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={style.Section}>
                <Spacer size={'l'}/>
                <motion.h1
                    viewport={{once: true}}
                    initial={{opacity: 0, y: 40}}
                    whileInView={{opacity: 1, y: 0}}
                    transition={{duration: 0.4, delay: 0.1}}
                >
                    <i>Women’s Labour Activism</i> is a public history project that tells the histories of women
                    activists
                    from Eastern, Central, and Southeastern Europe, who fought to improve women’s position in
                    the world of labour. The project seeks to amplify their contributions to struggles for a more
                    just society.
                </motion.h1>
                <Spacer size={'xxxl'}/>
                <motion.div
                    viewport={{once: true}}
                    initial={{opacity: 0, y: 40}}
                    whileInView={{opacity: 1, y: 0}}
                    transition={{duration: 0.4, delay: 0.2}}
                    className={style.AboutText}
                >
                    <div className={style.Left}/>
                    <div className={style.Right}>
                        This project is based on groundbreaking academic research carried out by a team of ten
                        scholars within the framework of “ZARAH: Women’s Labour Activism in Eastern Europe
                        and Transnationally, From the Age of Empires to the Late 20th Century”. This research
                        project, led by Susan Zimmermann at Central European University (Vienna, Austria), runs
                        between February 2020 and January 2026 and is funded by an ERC Advanced Grant (Grant
                        agreement no. 833691).
                    </div>
                </motion.div>
                <Spacer size={'xxxl'}/>
                <motion.div
                    viewport={{once: true}}
                    initial={{opacity: 0, y: 40}}
                    whileInView={{opacity: 1, y: 0}}
                    transition={{duration: 0.4, delay: 0.3}}
                    className={style.AboutText}
                >
                    <div className={style.Left}>
                        <h3>Further Readings</h3>
                        <br/>
                        If you want to learn more about women’s labour activism in Eastern, Central, and
                        Southeastern Europe and internationally, explore
                        the <Link href={"https://zarah-ceu.org/publications/"} target={'_blank'}>full list of academic
                            publications</Link> authored by the research team.
                    </div>
                    <div className={style.Right}/>
                </motion.div>
                <Spacer size={'xxxl'}/>
                <FurtherReadingSection/>
                <motion.div
                    viewport={{once: true}}
                    initial={{opacity: 0, y: 40}}
                    whileInView={{opacity: 1, y: 0}}
                    transition={{duration: 0.4, delay: 0.4}}
                    className={style.AboutText}
                >
                    <div className={style.Left}/>
                    <div className={style.Right}>
                        <h3>Copyright note</h3>
                        <br/>
                        Texts on this website are published under a Creative Commons Attribution-NonCommercial-
                        NoDerivatives 4.0 International licence <Link href={"https://creativecommons.org/licenses/by-nc-nd/4.0/"} target={'_blank'}>CC BY-NC-ND
                        4.0.</Link> This licence allows you to share,
                        copy, distribute and transmit the work for personal and non-commercial use provided author
                        attribution is clearly stated.
                    </div>
                </motion.div>
                <Spacer size={'xxxl'}/>
                <motion.div
                    viewport={{once: true}}
                    initial={{opacity: 0, y: 40}}
                    whileInView={{opacity: 1, y: 0}}
                    transition={{duration: 0.4, delay: 0.4}}
                    className={style.AboutText}
                >
                    <div className={style.Left}>
                        The author has attempted to contact potential copyright holders of illustrations contained on
                        this website. If there is anyone who claims copyright regarding any of the illustrations, please
                        contact the author.
                    </div>
                    <div className={style.Right}/>
                </motion.div>
                <Spacer size={'xxxl'}/>
            </div>
        </>
    )
}

Index.getLayout = function getLayout(page) {
    return (
        <LayoutDark>
            {page}
        </LayoutDark>
    )
}