import Head from "next/head";
import LayoutLight from "@/components/Layout/LayoutLight";
import Spacer from "@/components/BaseElements/Spacer";
import React, {useEffect, useRef, useState} from "react";
import styles from "./people.module.scss";
import {useRouter} from "next/router";
import PersonTile from "@/components/Cards/PersonTile/Desktop/PersonTile";
import {fetchPersonGroupsList} from "@/utils/api/fetchPersonGroups";
import {fetchPeopleList} from "@/utils/api/fetchPeople";
import {Media} from "@/utils/media";
import PersonTileMobile from "@/components/Cards/PersonTile/Mobile/PersonTileMobile";

export const getServerSideProps = (async (context) => {
    const [personGroupData, peopleData] = await Promise.all([
        fetchPersonGroupsList(),
        fetchPeopleList()
    ]);
    return {
        props: {
            personGroupData,
            peopleData
        }
    }
})


export default function PeoplePage({ personGroupData, peopleData }) {
    const groupNames = personGroupData['data'].map(group => group['Group']);

    const sectionRefs = useRef([]);
    const [activeGroup, setActiveGroup] = useState(groupNames[0]);
    const router = useRouter();

    // 🔁 Scroll to section on click with offset
    const scrollToGroup = (index) => {
        const ref = sectionRefs.current[index];
        if (ref) {
            const offset = 150;
            const elementTop = ref.getBoundingClientRect().top + window.scrollY;
            const scrollTo = elementTop - offset;

            window.scrollTo({ top: scrollTo, behavior: "smooth" });
        }
    };

    // ⬇️ On page load, scroll to section from hash
    useEffect(() => {
        const hash = decodeURIComponent(window.location.hash.substring(1));
        const index = groupNames.findIndex((name) => name.toLowerCase().replaceAll(' ', '-') === hash);
        if (index !== -1) {
            setTimeout(() => scrollToGroup(index), 300); // slight delay for layout to settle
        }
        setActiveGroup(groupNames[index] || groupNames[0]);
    }, []);

    const generatePeople = (group) => {
        return peopleData['data'].filter(person => {
            return person['PersonGroup']['Group'] === group['Group'];
        });
    }

    return (
        <>
            <Head>
                <title>Labour History Activism</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={styles.Section}>
                <Spacer size={'xl'} />
                <header className={styles.Header}>
                    {personGroupData['data'].map((group, index) => (
                        <p
                            key={group}
                            className={`${styles.GroupButton} ${
                                activeGroup === group['Group'] ? styles.Active : ""
                            }`}
                            onClick={() => {
                                scrollToGroup(index)
                                setActiveGroup(group['Group'])
                            }}
                        >
                            {group['Group']} ({group['People'].length})
                        </p>
                    ))}
                </header>

                <main className={styles.Main}>
                    {personGroupData['data'].map((group, index) => (
                        <section
                            key={group['id']}
                            ref={(el) => (sectionRefs.current[index] = el)}
                            className={styles.GroupSection}
                        >
                            <div className={styles.GroupHeader}>
                                <h2 className={styles.GroupTitle}>{group['Group']}</h2>
                                <p className={styles.GroupDescription}>{group['Description']}</p>
                            </div>
                            <Spacer size={'xl'}/>
                            <div className={styles.PeopleGrid}>
                                {generatePeople(group).map(person => (
                                     <>
                                         <Media greaterThanOrEqual="md">
                                             <PersonTile key={person.id} person={person} />
                                         </Media>
                                         <Media lessThan="md">
                                             <PersonTileMobile key={person.id} person={person} />
                                         </Media>
                                     </>
                                ))}
                            </div>
                            <Spacer size={'xl'}/>
                        </section>
                    ))}
                </main>
            </div>
        </>
    )
}

PeoplePage.getLayout = function getLayout(page) {
    return (
        <LayoutLight>
            {page}
        </LayoutLight>
    )
}