import Head from "next/head";
import LayoutDark from "@/components/Layout/LayoutDark";
import style from "./about.module.scss";
import Spacer from "@/components/BaseElements/Spacer";
import React from "react";
import FurtherReadingSection from "@/components/Sections/FurtherReadingSection/FurtherReadingSection";

export default function About() {
    return (
        <>
            <Head>
                <title>Labour History Activism</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={style.Section}>
                <Spacer size={'medium'}/>
                <h1>
                    Women’s Labour Activism is a public history project that tells the stories of women
                    activists from Eastern and Central Europe who fought for the improvement of women’s
                    position in the world of labour. It aims to amplify their contribution to the struggle
                    for a fairer world.
                </h1>
                <Spacer size={'xxlarge'}/>
                <div className={style.AboutText}>
                    <div className={style.Left}/>
                    <div className={style.Right}>
                            It bases on the path-breaking academic research conducted by a team of ten scholars within
                            the framework of “ZARAH: Women’s labour activism in Eastern Europe and transnationally,
                            from the age of empires to the late 20th century”, a research project led by Prof.
                            Susan Zimmermann and based at Central European University (Vienna, Austria) between
                            February 2020 and January 2026, and funded by an ERC Advanced Grant (Grant agreement no. 833691).
                    </div>
                </div>
                <Spacer size={'large'}/>
                <FurtherReadingSection />
            </div>
        </>
    )
}

About.getLayout = function getLayout(page) {
    return (
        <LayoutDark>
            {page}
        </LayoutDark>
    )
}