import Head from "next/head";
import EssaySection from "@/components/Sections/EssaySection/EssaySection";
import LayoutLight from "@/components/Layout/LayoutLight";
import Spacer from "@/components/BaseElements/Spacer";
import React from "react";
import style from "./essays.module.scss";

export default function Essays() {
    return (
        <>
            <Head>
                <title>Labour History Activism</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={style.Section}>
                <Spacer size={'medium'}/>
                <EssaySection header={false} max={0}/>
            </div>
        </>
    )
}

Essays.getLayout = function getLayout(page) {
    return (
        <LayoutLight>
            {page}
        </LayoutLight>
    )
}