import Head from "next/head";
import Layout from "@/components/Layout/Layout";
import style from "./index.module.scss";
import OpeningAnimation from "@/components/Sections/OpeningAnimation/OpeningAnimation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Labour History Activism</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout theme={'dark'}>
            <OpeningAnimation/>
            <div className={style.Section2}>
                adfadf
            </div>
        </Layout>
    </>
  );
}
