import Head from "next/head";
import OpeningAnimation from "@/components/Sections/OpeningAnimation/OpeningAnimation";
import HorizontalScrollSection from "@/components/Sections/SectionTitleAnimation/SectionTitleAnimation";
import ActivismTypeSelector from "@/components/Sections/ActivisimsSelector/ActivismsSelector";
import PeopleSection from "@/components/Sections/PeopleSection/PeopleSection";
import EssaySection from "@/components/Sections/EssaySection/EssaySection";
import LayoutDark from "@/components/Layout/LayoutDark";
import {fetchEssaysFrontPage} from "@/utils/api/fetchEassys";
import {fetchActivismTypesFrontPage} from "@/utils/api/fetchActivismTypes";
import {fetchPeopleFrontPage} from "@/utils/api/fetchPeople";

export const getServerSideProps = (async (context) => {
  const [essayData, activismTypeData, peopleData] = await Promise.all([
    fetchEssaysFrontPage(),
    fetchActivismTypesFrontPage(),
    fetchPeopleFrontPage()
  ]);

  return {
    props: {
      essayData,
      activismTypeData,
      peopleData
    }
  }
})

export default function Home({essayData, activismTypeData, peopleData}) {
    return (
    <>
      <Head>
        <title>Women's Labour Activism</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <OpeningAnimation/>
        <HorizontalScrollSection text={'Activism'} />
        <ActivismTypeSelector data={activismTypeData['data']} />
        <HorizontalScrollSection text={'People'} />
        <PeopleSection data={peopleData['data']} />
        <EssaySection data={essayData['data']} />
    </>
  )
}

Home.getLayout = function getLayout(page) {
  return (
      <LayoutDark>
        {page}
      </LayoutDark>
  )
}
