import Head from "next/head";
import style from "./networks.module.scss";
import Spacer from "@/components/BaseElements/Spacer";
import React from "react";
import LayoutLight from "@/components/Layout/LayoutLight";
import dynamic from "next/dynamic";

const SVGMap = dynamic(() => import("@/components/Map/Map"), {
    ssr: false,
});


export default function Networks() {
    return (
        <>
            <Head>
                <title>Labour History Activism</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={style.Section}>
                <Spacer size={'l'}/>
                <div className={style.NetworksHeader}>
                    <div className={style.Left}>
                        <h1>Networks</h1>
                    </div>
                    <div className={style.Right}>
                        <p>
                        Throughout history, women not only faced barriers to certain professions and types of jobs,
                        but also were excluded from positions within the state apparatus. When governments started
                        to include women in the ranks of state administration, some of these officials used their
                        position to improve the lot of women in the world of labour. Often engaged in research,
                        policy-making, these women aimed to shed light on the condition of women workers and advance
                        social change. This cluster showcases their work throughout the twentieth century.
                        </p>
                    </div>
                </div>
                <Spacer size={'xxl'} />
                <div className={style.MapContainer}>
                    <SVGMap />
                </div>
            </div>
        </>
    )

}

Networks.getLayout = function getLayout(page) {
    return (
        <LayoutLight>
            {page}
        </LayoutLight>
    )
}