import Head from "next/head";
import EssaySection from "@/components/Sections/EssaySection/EssaySection";
import LayoutLight from "@/components/Layout/LayoutLight";

export default function Essays() {
    return (
        <>
            <Head>
                <title>Labour History Activism</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <EssaySection header={false} max={0}/>
        </>
    )
}

Essays.getLayout = function getLayout(page) {
    return (
        <LayoutLight>
            {page}
        </LayoutLight>
    )
}