import Head from "next/head";
import EssaySection from "@/components/Sections/EssaySection/EssaySection";
import LayoutLight from "@/components/Layout/LayoutLight";
import Spacer from "@/components/BaseElements/Spacer";
import React from "react";
import style from "./essays.module.scss";
import {fetchEssaysList} from "@/utils/api/fetchEassys";

export const getServerSideProps = (async (context) => {
    const [essayData] = await Promise.all([
        fetchEssaysList(),
    ]);
    return {
        props: {
            essayData,
        }
    }
})

export default function EssaysPage({essayData}) {
    return (
        <>
            <Head>
                <title>Labour History Activism</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={style.Section}>
                <Spacer size={'l'}/>
                <EssaySection header={false} data={essayData['data']} />
            </div>
        </>
    )
}

EssaysPage.getLayout = function getLayout(page) {
    return (
        <LayoutLight>
            {page}
        </LayoutLight>
    )
}