import React, { useState, useEffect } from "react";
import styles from "./search.module.scss";
import LayoutLight from "@/components/Layout/LayoutLight";
import Head from "next/head";
import Spacer from "@/components/BaseElements/Spacer";
import { Meilisearch } from "meilisearch";
import {useRouter} from "next/router";

const server = process.env.NEXT_PUBLIC_MEILISEARCH_URL
const apiKey = process.env.NEXT_PUBLIC_MEILISEARCH_API_KEY

export default function SearchPage() {
    const [query, setQuery] = useState("");
    const [searchQuery, setSearchQuery] = useState("");

    const [facets, setFacets] = useState({});
    const [selectedTags, setSelectedTags] = useState([]);

    const router = useRouter();

    async function doSearch() {
        const client = new Meilisearch({
            host: server,
            apiKey: apiKey,
        })

        const index = client.index('labouractivism')

        const getFilters = () => {
            let filters = ""
            selectedTags.forEach ((tag) => {
                filters = `Tags=${tag}`
            })
            return filters
        }

        const options = {
            facets: ['Tags'],
            limit: 0
        }
        if (getFilters().length > 0) {
            options['filter'] = getFilters()
        }

        const search = await index.search(searchQuery, options)

        const tags = Object.keys(search['facetDistribution']['Tags'] || [])

        // Group tags alphabetically
        const grouped = {};
        tags.forEach(tag => {
            const letter = tag[0].toUpperCase();
            if (!grouped[letter]) grouped[letter] = [];
            grouped[letter].push(tag);
        });
        setFacets(grouped);
    }

    // Simulating Meilisearch response (replace with real API call)
    useEffect(() => {
        doSearch();
    }, []);

    useEffect(() => {
        doSearch()
        handleSearch()
    }, [searchQuery, selectedTags]);

    const handleSearch = () => {
        if (query === "") {
            router.push({
                pathname: "/search",
            });
        } else {
            router.push({
                pathname: "/search",
                query: { q: query },
            });
        }
    };

    const splitIntoColumns = (sortedKeys, numCols) => {
        const perCol = Math.ceil(sortedKeys.length / numCols);
        const cols = [];
        for (let i = 0; i < numCols; i++) {
            cols.push(sortedKeys.slice(i * perCol, (i + 1) * perCol));
        }
        return cols;
    }

    return (
        <>
            <Head>
                <title>Labour History Activism - Search</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.Section}>
                <Spacer size={'xxl'}/>

                {/* Search Bar */}
                <div className={styles.SearchBar}>
                    <div className={styles.InputWrapper}>
                        <input
                            type="text"
                            placeholder="I am interested in..."
                            value={query}
                            onChange={(e) => setQuery(e.target.value)}
                            onKeyDown={(e) => {
                                if (e.key === "Escape") {
                                    setQuery("");
                                    setSearchQuery("");
                                }
                                if (e.key === "Enter") {
                                    e.preventDefault();
                                    setSearchQuery(query);
                                }
                            }}
                        />
                        {query && (
                            <button
                                type="button"
                                className={styles.ClearButton}
                                onClick={() => {
                                    setQuery("")
                                    setSearchQuery("")}
                                }
                                aria-label="Clear search input"
                            >
                                ×
                            </button>
                        )}
                    </div>
                    <button onClick={(e) => setSearchQuery(query)}>
                        <h1>Search</h1>
                    </button>
                </div>

                <Spacer size={'xxl'}/>

                {/* Alphabet Navigation */}
                <div className={styles.AlphabetNav}>
                    {"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map((letter) => (
                        <span
                            key={letter}
                            onClick={() => {
                                if (Object.keys(facets).includes(letter)) {
                                    const el = document.getElementById(`facet-${letter}`);
                                    if (el) {
                                        el.scrollIntoView({behavior: "smooth", block: "start", offset: 100});
                                    }
                                }
                            }}
                            className={Object.keys(facets).includes(letter) ? styles.Letter : `${styles.Letter} ${styles.Disabled}`}
                        >
                          {letter}
                        </span>
                    ))}
                </div>

                <Spacer size={'l'}/>

                {/* Facet Groups */}
                <div className={styles.Facets}>
                    {splitIntoColumns(Object.keys(facets).sort(), 4).map((col, colIdx) => (
                        <div key={colIdx} className={styles.Columns}>
                            {col.map((letter) => (
                                <div key={letter} id={`facet-${letter}`} className={styles.FacetGroup}>
                                    <h2>{letter}</h2>
                                    <ul>
                                        {facets[letter].map((tag) => (
                                            <li key={tag} onClick={() => setSelectedTags([tag])}>{tag}</li>
                                        ))}
                                    </ul>
                                </div>
                            ))}
                        </div>
                    ))}
                </div>

                <Spacer size={'xxl'}/>
            </div>
        </>
    );
}

SearchPage.getLayout = function getLayout(page) {
    return (
        <LayoutLight>
            {page}
        </LayoutLight>
    )
}
