import React, { useState, useEffect } from "react";
import styles from "./search.module.scss";
import LayoutLight from "@/components/Layout/LayoutLight";
import Head from "next/head";
import Spacer from "@/components/BaseElements/Spacer";
import { Meilisearch } from "meilisearch";
import {useRouter} from "next/router";
import FiltersPage from "@/components/Search/FiltersPage";
import {useList, useSet} from "react-use";
import TagFilterButton from "@/components/BaseElements/TagFilterButton";
import ResultsPage from "@/components/Search/ResultsPage";

const server = process.env.NEXT_PUBLIC_MEILISEARCH_URL
const apiKey = process.env.NEXT_PUBLIC_MEILISEARCH_API_KEY

export default function SearchPage() {
    const [query, setQuery] = useState("");
    const [searchQuery, setSearchQuery] = useState("");
    const [selectedTags, { add, remove }] = useSet(new Set([]));

    const [hits, setHits] = useState([]);
    const [facets, setFacets] = useState({});

    const [view, setView] = useState("filters");

    const router = useRouter();

    async function doSearch() {
        const client = new Meilisearch({
            host: server,
            apiKey: apiKey,
        })

        const index = client.index('labouractivism')

        const getFilters = () => {
            const filters = []
            selectedTags.forEach ((tag) => {
                filters.push(`Tags='${tag}'`)
            })
            return filters.join(' AND ')
        }

        const options = {
            facets: ['Tags'],
            limit: 20
        }
        if (getFilters().length > 0) {
            options['filter'] = getFilters()
        }

        const search = await index.search(searchQuery, options)
        const tags = Object.keys(search['facetDistribution']['Tags'] || [])

        setHits(search['hits'])

        // Group tags alphabetically
        const grouped = {};
        tags.forEach(tag => {
            const letter = tag[0].toUpperCase();
            if (!grouped[letter]) grouped[letter] = [];
            grouped[letter].push(tag);
        });
        setFacets(grouped);
    }

    // Simulating Meilisearch response (replace with real API call)
    useEffect(() => {
        doSearch();
    }, []);

    useEffect(() => {
        doSearch()
        changeRoute()
    }, [searchQuery, selectedTags]);

    const changeRoute = () => {
        const params = {}

        if (searchQuery === "") {
            delete params['query']
        } else {
            params['q'] = searchQuery
        }

        if ([...selectedTags].length > 0) {
            params['tags'] = [...selectedTags]
        }

        router.push({
            pathname: "/search",
            query: params,
        }, undefined, { shallow: true });
    };

    const addTag = (tag) => {
        add(tag)
        setView('results')
    }

    const removeTag = (tag) => {
        remove(tag)
    }

    const renderSearchContent = () => {
        if (view === 'filters') {
            return <FiltersPage facets={facets} onSetSelectedTags={addTag} />
        } else {
            return <ResultsPage hits={hits} />
        }
    }

    return (
      <>
          <Head>
              <title>Labour History Activism - Search</title>
              <meta name="description" content="Generated by create next app"/>
              <meta name="viewport" content="width=device-width, initial-scale=1"/>
              <link rel="icon" href="/favicon.ico"/>
          </Head>
          <div className={styles.Section}>
              <Spacer size={'xxl'}/>

              {/* Search Bar */}
              <div className={styles.SearchBar}>
                  <div className={styles.InputWrapper}>
                      <input
                        type="text"
                        placeholder="I am interested in..."
                        value={query}
                        onChange={(e) => setQuery(e.target.value)}
                        onKeyDown={(e) => {
                            if (e.key === "Escape") {
                                setQuery("");
                                setSearchQuery("");
                            }
                            if (e.key === "Enter") {
                                e.preventDefault();
                                setSearchQuery(query);
                            }
                        }}
                      />
                      {query && (
                        <button
                          type="button"
                          className={styles.ClearButton}
                          onClick={() => {
                              setQuery("")
                              setSearchQuery("")}
                          }
                          aria-label="Clear search input"
                        >
                            ×
                        </button>
                      )}
                  </div>
                  <button onClick={(e) => setSearchQuery(query)} className={styles.SearchButton}>
                      <h1>Search</h1>
                  </button>
              </div>
              <div className={styles.ViewChanger}>
                  <div className={styles.SelectedTags}>
                      {
                          [...selectedTags].map(tag => {
                              return <TagFilterButton label={tag} onRemove={removeTag}/>
                          })
                      }
                  </div>
                  <button
                    className={styles.ViewChangerButton}
                    onClick={(e) => setView(view === 'filters' ? 'results' : 'filters')}>
                      <h5>{view === 'filters' ? 'Show Results' : 'Show Filters'}</h5>
                  </button>
              </div>

              <Spacer size={'xxl'}/>
              {renderSearchContent()}
              <Spacer size={'xxl'}/>
          </div>
      </>
    );
}

SearchPage.getLayout = function getLayout(page) {
    return (
      <LayoutLight>
          {page}
      </LayoutLight>
    )
}
