import styles from "./ActivismTypesSection.module.scss";
import React, {useState} from "react";
import Head from "next/head";
import ActivismSection from "@/components/Sections/Activisims/ActivismSection";

const ActivismTypesSectionMobile = ({activismTypeData}) => {
    const [activeType, setActiveType] = useState(activismTypeData['data'][0]['Type']);

    const renderTypeSelectors = () => {
        return (
            <div className={styles.TypeSelectors}>
                {
                    activismTypeData['data'].map((data, idx) => {
                        return (<span className={activeType === data['Type'] ? styles.Active : ''}
                                      onClick={() => setActiveType(data['Type'])}>{data['Type']}</span>)
                    })
                }
            </div>
        )
    }

    const renderActiveTypeContent = () => {
        const group = activismTypeData['data'].find(group => group['Type'] === activeType);
        return <ActivismSection group={group} />
    }

    return (
        <>
            <Head>
                <title>Labour History Activism - Activism</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.Section}>
                <header>
                    {renderTypeSelectors()}
                    {renderActiveTypeContent()}
                </header>
            </div>
        </>
    )
}

export default ActivismTypesSectionMobile