import styles from "./ActivismTypesSection.module.scss";
import React, {useEffect, useState} from "react";
import Head from "next/head";
import ActivismSection from "@/components/Sections/Activisims/ActivismSection";
import Spacer from "@/components/BaseElements/Spacer";

const ActivismTypesSectionMobile = ({activismTypeData}) => {
    const defaultType = activismTypeData["data"][0]["Type"];
    const [activeType, setActiveType] = useState(defaultType);

    // Helper to sync state with hash
    const setTypeFromHash = () => {
        if (window.location.hash) {
            const hashType = decodeURIComponent(window.location.hash.substring(1));
            const exists = activismTypeData["data"].some((d) => d["Type"] === hashType);
            if (exists) {
                setActiveType(hashType);
            }
        }
    };

    // On mount, check hash
    useEffect(() => {
        setTypeFromHash();

        // Listen for hash changes (back/forward/manual edit)
        window.addEventListener("hashchange", setTypeFromHash);

        return () => {
            window.removeEventListener("hashchange", setTypeFromHash);
        };
    }, [activismTypeData]);

    // Update hash when activeType changes
    useEffect(() => {
        if (activeType) {
            window.history.replaceState(null, "", `#${encodeURIComponent(activeType)}`);
        }
    }, [activeType]);

    const renderTypeSelectors = () => {
        return (
            <div className={styles.TypeSelectors}>
                {
                    activismTypeData['data'].map((data, idx) => {
                        return (<span
                            key={idx}
                            className={activeType === data['Type'] ? styles.Active : ''}
                            onClick={() => setActiveType(data['Type'])}>{data['Type']}</span>)
                    })
                }
            </div>
        )
    }

    const renderActiveTypeContent = () => {
        const group = activismTypeData['data'].find(group => group['Type'] === activeType);
        return <ActivismSection group={group} />
    }

    return (
        <>
            <Head>
                <title>Labour History Activism - Activism</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.Section}>
                <header>
                    {renderTypeSelectors()}
                    <Spacer size={'xl'}/>
                    {renderActiveTypeContent()}
                </header>
            </div>
        </>
    )
}

export default ActivismTypesSectionMobile