import styles from "./ActivismTypesSection.module.scss";
import React, {useEffect, useRef, useState} from "react";
import Head from "next/head";
import ActivismSection from "@/components/Sections/Activisims/ActivismSection";
import Spacer from "@/components/BaseElements/Spacer";
import {useEffectOnce} from "react-use";

const ActivismTypesSectionMobile = ({activismTypeData}) => {
    const defaultType = activismTypeData["data"][0]["Type"];
    const [activeType, setActiveType] = useState(defaultType);

    const [isScrollingUp, setIsScrollingUp] = useState(true);
    const lastScrollY = useRef(0);

    // detect scroll direction (only mobile, max-width: 800px)
    useEffect(() => {
        const handleScroll = () => {
            const currentScrollY = window.scrollY;
            if (window.innerWidth <= 800) {
                if (currentScrollY > lastScrollY.current && currentScrollY > 100) {
                    // scrolling down
                    setIsScrollingUp(false);
                } else {
                    // scrolling up
                    setIsScrollingUp(true);
                }
            }
            lastScrollY.current = currentScrollY;
        };

        window.addEventListener("scroll", handleScroll);
        return () => window.removeEventListener("scroll", handleScroll);
    }, []);

    // On mount, check hash
    useEffectOnce(() => {
        const hash = decodeURIComponent(window.location.hash.slice(1));
        const index = activismTypeData.data.findIndex(
            (group) => group.Type.replace(/\s+/g, "-") === hash
        );

        if (index !== -1) {
            setTimeout(() => {
                setActiveType(activismTypeData["data"][index]["Type"]);
            }, 200);
        }}
    );

    const renderTypeSelectors = () => {
        return (
            <div className={`${styles.TypeSelectors} ${
                isScrollingUp ? styles.Show : styles.Hide
            }`}>
                {
                    activismTypeData['data'].map((data, idx) => {
                        return (<span
                            key={idx}
                            className={activeType === data['Type'] ? styles.Active : ''}
                            onClick={() => {
                                setActiveType(data['Type']);
                                window.scrollTo({ top: 0, behavior: "smooth" });
                            }}>{data['Type']}</span>)
                    })
                }
            </div>
        )
    }

    const renderActiveTypeContent = () => {
        const group = activismTypeData['data'].find(group => group['Type'] === activeType);
        return <ActivismSection group={group} />
    }

    return (
        <>
            <Head>
                <title>Labour History Activism - Activism</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.Section}>
                <header>
                    {renderTypeSelectors()}
                    <Spacer size={'xl'}/>
                    {renderActiveTypeContent()}
                </header>
            </div>
        </>
    )
}

export default ActivismTypesSectionMobile